### ISSUE TITLE
Is there a bug in Self_Attn module?

### ISSUE THREAD

**Issue by ognkrmms** [heykeetae/Self-Attention-GAN#7]
Hi,

I noticed something strange in sagan_models.py. In the original paper matrix multiplication is used to calculate f_x * g_x and also h_x * attn_score. However, in the code torch.mul() is used which is an elementwise multiplication operation. I think you meant to use torch.matmul().

**Comment by affromero** [comment]
Also, according to the paper softmax is performed on each row. Is https://github.com/heykeetae/Self-Attention-GAN/blob/master/sagan_models.py#L43 (dim=1) not choosing columns instead?

@ognkrmms I agree with you in the first part (f_x * g_x). However, it does not make sense for the h_x * attn_score part to be _matmul_ because of the softmax probability distribution, don't you think?

@ognkrmms @heykeetae do you know some theoretical explanation either for _matmul_ or _mul_ at the very first part?

**Comment by heykeetae** [comment]
We have updated the 'sagan_models.py'. please check it out!
